### ISSUE TITLE
啥垃圾代码 就这玩意也提交?

### ISSUE THREAD

**Issue by iuue16129** [reprover/amap#5]
composer.json autoload用psr-0? 请问你是认真的吗
接口用http请求就不怪你了
src/Support/Result.php 你好歹把你家的dump注释掉啊
你这13个start是招人刷的吧? 还是哪位小哥乱点点到了
不会写包就别特么写 浪费大家时间

附上使用该代码方法
下载源文件 放入项目某个位置
将composer.json中psr-0改成psr-4
根目录中的composer.json 
```
"autoload": {
    "psr-4": {
      "Reprover\\Amap\\": "path/src"
    }
  },
```

记得把src/Support/Result.php line:33 dump 去掉
某些接口请求地址变了要改一下
目前就这么多

**Comment by reprover** [comment]
如果你前面没写那些我谢谢你

你特么牛呗，没看见你有几个star啊。不会说话就别说，ok？

提个建议非得先喷一下？

劳资写这个时刚学composer，找人刷也不会只刷13个，逗。
